name: .NET CI - Advanced Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore NetCICDPortfolioDemo.slnx

    - name: Build project
      run: dotnet build NetCICDPortfolioDemo.slnx --no-restore --configuration Release

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore NetCICDPortfolioDemo.slnx

    - name: Run unit tests
      run: dotnet test NetCICDPortfolioDemo.Tests/NetCICDPortfolioDemo.Tests.csproj --configuration Release --verbosity normal

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish for IIS
        run: dotnet publish --no-build --configuration Release -o ./publish-iis --runtime win-x64 --self-contained false

      - name: Save IIS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iis-publish
          path: ./publish-iis
          retention-days: 7

  docker-build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/netcicdportfoliodemo:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/netcicdportfoliodemo:${{ github.sha }}

